'use strict';
const $=s=>document.querySelector(s);
const node=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
const fmt=n=>Number.isFinite(n)?n.toFixed(2):'—';
let data, selectedGame, liveData, liveEndpoint, feedFailed=false;
const team=id=>data.teams.find(t=>t.id===id);
function logo(t){const fallback=()=>node('span',t.name.split(/\s+/).map(s=>s[0]).slice(0,3).join(''),'logo initials');if(!t.logo)return fallback();const img=node('img','','logo');img.src=t.logo;img.alt=t.name+' logo';img.loading='lazy';img.addEventListener('error',()=>img.replaceWith(fallback()),{once:true});return img;}
function metrics(through){const weeks=data.weeks.filter(w=>w.week<=through);if(!weeks.length)return [];const rows=data.teams.map(t=>({...t,scores:[],faced:[],wins:0,allplay:0}));const lookup=new Map(rows.map(t=>[t.id,t]));for(const w of weeks){const scores=new Map();for(const g of w.matchups){scores.set(g.team_id,g.points);scores.set(g.opponent_id,g.opponent_points);for(const [id,p,o] of [[g.team_id,g.points,g.opponent_points],[g.opponent_id,g.opponent_points,g.points]]){const r=lookup.get(id);r.scores.push(p);r.faced.push(o);r.wins+=p>o?1:p===o?.5:0;}}for(const [id,p] of scores){lookup.get(id).allplay+=[...scores].filter(([other])=>id!==other).reduce((a,[,q])=>a+(p>q?1:p===q?.5:0),0)/(scores.size-1);}}
 const total=a=>a.reduce((x,y)=>x+y,0);for(const r of rows){r.total=total(r.scores);r.avg=r.total/weeks.length;r.pa=total(r.faced)/weeks.length;r.ap=r.allplay/weeks.length;r.luck=r.wins-r.allplay;r.low=Math.min(...r.scores);r.high=Math.max(...r.scores);}
 const percentile=(r,key)=>rows.filter(x=>x.id!==r.id).reduce((a,x)=>a+(key(r)>key(x)?1:key(r)===key(x)?.5:0),0)/(rows.length-1);
 for(const r of rows)r.index=100*(.5*percentile(r,t=>t.total)+.3*r.ap+.2*percentile(r,t=>t.scores.at(-1)));
 return rows.sort((a,b)=>b.index-a.index||a.name.localeCompare(b.name));}
function weekData(){const n=Number($('#week').value);if(liveData?.week===n)return liveData;return data.weeks.find(w=>w.week===n)||{week:n,matchups:data.schedule.filter(g=>g.week===n),starters:[],top_players:[],scheduled:true};}
function side(id){const t=team(id),s=node('div','','team-side');s.append(logo(t),node('span',t.name,'team-name'));return s;}
function openGame(g,w){selectedGame={g,w};$('#detail-week').textContent=`WEEK ${w.week} / ${w.live?(WFCLive.stale(w)||feedFailed?'DELAYED':g.status.toUpperCase()):w.scheduled?'UNVERIFIED SCHEDULE':'FINAL'}`;$('#detail-title').textContent=`${team(g.team_id).name} vs. ${team(g.opponent_id).name}`;const score=$('#detail-score');score.className='detail-score';score.textContent=w.scheduled?'Awaiting scoring feed':`${fmt(g.points)} — ${fmt(g.opponent_points)}`;
 const history=metrics(w.week-1),a=history.find(t=>t.id===g.team_id),b=history.find(t=>t.id===g.opponent_id);
 $('#preview').textContent=a&&b?`Entering Week ${w.week}, ${a.name} averaged ${fmt(a.avg)} points and finished ahead of the league in ${(a.ap*100).toFixed(0)}% of weekly comparisons, while ${b.name} averaged ${fmt(b.avg)} and finished ahead in ${(b.ap*100).toFixed(0)}%. Their weekly scoring ranges were ${fmt(a.low)}–${fmt(a.high)} and ${fmt(b.low)}–${fmt(b.high)}. ${history[0].scores.length<4?'Early-season sample: treat these comparisons cautiously.':''}`:'No earlier verified weeks are available for a pregame comparison.';
 $('#probability-note').textContent=w.live&&g.win_probability!==null?`${team(g.team_id).name}: ${(g.win_probability*100).toFixed(0)}% win probability. Method: ${g.probability_method}. ${(WFCLive.stale(w)||feedFailed)?'Feed delayed; probability may be outdated.':''}`:'Win probability is unavailable: this snapshot has no live projections or remaining-player estimates.';
 $('#rosters').replaceChildren(...[g.team_id,g.opponent_id].map(id=>{const box=node('div');box.append(node('h3',team(id).name));const starters=w.starters.filter(p=>p.team_id===id);if(!starters.length)box.append(node('p','Starting lineup and live player stats are awaiting a scoring feed.','empty'));for(const p of starters){const row=node('div','','roster-row');row.append(node('span',p.slot),node('span',p.player+(p.statline?' · '+p.statline:'')),node('strong',fmt(p.points)));box.append(row);}if(starters.length)box.append(node('p',`Starter total: ${fmt(starters.reduce((s,p)=>s+p.points,0))} · ${w.live?'Feed fantasy points':'Final fantasy points'}`,'muted'));return box;}));if(!$('#detail').open)$('#detail').showModal();}
function render(){const w=weekData(),through=Math.min(w.week,data.weeks.at(-1).week),rows=metrics(through),previous=metrics(through-1);$('#status').textContent=`${data.season} · Week ${w.week} · ${w.live?(WFCLive.stale(w)||feedFailed?'Delayed feed':gStatus(w)):w.scheduled?'Schedule only — results not verified':'Final results'}`;$('#matchups').replaceChildren(...w.matchups.map(g=>{const card=node('button','','game');card.type='button';card.setAttribute('aria-label',`${team(g.team_id).name} vs ${team(g.opponent_id).name}, view matchup`);card.append(node('div',w.live?`${g.status.toUpperCase()} / OPEN MATCHUP ↗`:w.scheduled?'SCHEDULE ONLY / OPEN MATCHUP ↗':'FINAL / OPEN MATCHUP ↗','game-status'));const face=node('div','','faceoff'),center=node('div');center.append(node('div',w.scheduled?'— : —':`${fmt(g.points)} : ${fmt(g.opponent_points)}`,'scoreline'));const bar=node('div','','prob-bar');bar.setAttribute('aria-hidden','true');if(w.live&&g.win_probability!==null){for(const fraction of [g.win_probability,1-g.win_probability]){const fill=node('span');fill.style.width=fraction*100+'%';bar.append(fill);}}center.append(bar,node('div',w.live&&g.win_probability!==null?`${Math.round(g.win_probability*100)}% / ${Math.round((1-g.win_probability)*100)}% win chance`:'Win probability unavailable','prob-label'));face.append(side(g.team_id),center,side(g.opponent_id));card.append(face);card.onclick=()=>openGame(g,w);return card;}));
 $('#power').replaceChildren(...rows.map((t,i)=>{const row=node('div','','rank-row'),name=node('div');name.append(node('div',t.name,'rank-name'),node('div',`${fmt(t.avg)} PPG · ${(100*t.ap).toFixed(0)}% league strength`,'rank-meta'));const meter=node('div','','meter'),fill=node('span');fill.style.width=t.index+'%';meter.append(fill);name.append(meter);const value=node('div',t.index.toFixed(1),'index-value');const old=previous.findIndex(p=>p.id===t.id),change=old-i;value.append(node('span',old<0?'NEW':change>0?`↑ ${change}`:change<0?`↓ ${-change}`:'—','movement'));row.append(node('span',String(i+1).padStart(2,'0'),'rank-number'),logo(t),name,value);return row;}));
 $('#players').replaceChildren(...w.top_players.map((p,i)=>{const row=node('div','','player'),name=node('div');name.append(node('strong',p.player),node('small',`${p.position} · ${p.team}`));row.append(node('span',String(i+1).padStart(2,'0'),'rank-number'),name,node('span',fmt(p.points),'points'));return row;}));if(!w.top_players.length)$('#players').append(node('p','A verified all-roster scoring export is needed for this week’s top 10.','empty'));
 renderCharts(rows,through);}
const NS='http://www.w3.org/2000/svg';function svgEl(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
function chart(id,label){const s=svgEl('svg',{viewBox:'0 0 480 285',role:'img','aria-label':label});s.append(svgEl('title',{},label));$('#'+id).replaceChildren(s);return s;}
function renderCharts(rows,through){const scatter=chart('scatter','Team scoring strength versus opponent scoring. Hover a logo for exact averages.');const values=rows.flatMap(t=>[t.avg,t.pa]),lo=Math.floor((Math.min(...values)-10)/20)*20,hi=Math.ceil((Math.max(...values)+10)/20)*20;const x=v=>55+(v-lo)/(hi-lo)*390,y=v=>235-(v-lo)/(hi-lo)*200;for(let v=lo;v<=hi;v+=(hi-lo)/4){scatter.append(svgEl('line',{x1:55,x2:445,y1:y(v),y2:y(v),class:'gridline'}),svgEl('text',{x:45,y:y(v)+4,'text-anchor':'end'},v.toFixed(0)),svgEl('text',{x:x(v),y:253,'text-anchor':'middle'},v.toFixed(0)));}scatter.append(svgEl('text',{x:245,y:279,'text-anchor':'middle'},'OPPONENT AVERAGE →'),svgEl('text',{x:55,y:15},'POINTS SCORED ↑'));for(const t of rows){const g=svgEl('g');g.append(svgEl('title',{},`${t.name}: ${fmt(t.avg)} scored / ${fmt(t.pa)} faced`),svgEl('circle',{cx:x(t.pa),cy:y(t.avg),r:7,fill:'#bcf047',stroke:'#071322','stroke-width':2}));if(t.logo)g.append(svgEl('image',{href:t.logo,x:x(t.pa)-12,y:y(t.avg)-12,width:24,height:24}));scatter.append(g);}
 renderTrend(through);
 const maxLuck=Math.max(1,...rows.map(t=>Math.abs(t.luck))),maxScore=Math.max(...rows.map(t=>t.high))*1.05;
 for(const kind of ['luck','range'])$('#'+kind).replaceChildren(...[...rows].sort((a,b)=>kind==='luck'?b.luck-a.luck:b.avg-a.avg).map(t=>{const row=node('div','','analytic-row'),rail=node('div','','rail'),fill=node('span','','fill');if(kind==='luck'){fill.style.left=(t.luck<0?50+t.luck/maxLuck*50:50)+'%';fill.style.width=Math.abs(t.luck)/maxLuck*50+'%';if(t.luck<0)fill.style.background='#4a9eff';rail.append(node('span','','zero'));row.title=`${t.name}: ${t.wins} actual H2H wins minus ${t.allplay.toFixed(2)} expected`;}else{fill.classList.add('range-fill');fill.style.left=t.low/maxScore*100+'%';fill.style.width=(t.high-t.low)/maxScore*100+'%';const dot=node('span','','dot');dot.style.left=t.avg/maxScore*100+'%';rail.append(dot);row.title=`${t.name}: low ${fmt(t.low)}, average ${fmt(t.avg)}, high ${fmt(t.high)}`;}rail.append(fill);row.append(node('span',t.name),rail,node('span',kind==='luck'?`${t.luck>0?'+':''}${t.luck.toFixed(2)}`:t.avg.toFixed(1)));return row;}));}
function renderTrend(through){const s=chart('trend','Weekly range, league mean and selected team scoring'),weeks=data.weeks.filter(w=>w.week<=through),id=$('#chart-team').value;const series=weeks.map(w=>{const vals=w.matchups.flatMap(g=>[g.points,g.opponent_points]);const game=w.matchups.find(g=>g.team_id===id||g.opponent_id===id);return {week:w.week,lo:Math.min(...vals),hi:Math.max(...vals),avg:vals.reduce((a,b)=>a+b,0)/vals.length,point:game.team_id===id?game.points:game.opponent_points};});const lo=Math.floor(Math.min(...series.map(s=>s.lo))/25)*25,hi=Math.ceil(Math.max(...series.map(s=>s.hi))/25)*25,x=i=>weeks.length===1?245:55+i/(weeks.length-1)*380,y=v=>235-(v-lo)/(hi-lo||1)*195;for(let i=0;i<5;i++){const v=lo+(hi-lo)*i/4;s.append(svgEl('line',{x1:55,x2:445,y1:y(v),y2:y(v),class:'gridline'}),svgEl('text',{x:45,y:y(v)+4,'text-anchor':'end'},v.toFixed(0)));}s.append(svgEl('polyline',{points:series.map((t,i)=>`${x(i)},${y(t.avg)}`).join(' '),fill:'none',stroke:'#70879d','stroke-dasharray':'5 5','stroke-width':2}),svgEl('polyline',{points:series.map((t,i)=>`${x(i)},${y(t.point)}`).join(' '),fill:'none',stroke:'#bcf047','stroke-width':3}));series.forEach((t,i)=>{const g=svgEl('g');g.append(svgEl('title',{},`Week ${t.week}: ${team(id).name} ${fmt(t.point)}; league mean ${fmt(t.avg)}; range ${fmt(t.lo)}–${fmt(t.hi)}`),svgEl('line',{x1:x(i),x2:x(i),y1:y(t.lo),y2:y(t.hi),stroke:'#4a9eff','stroke-width':10,opacity:.22}),svgEl('circle',{cx:x(i),cy:y(t.point),r:5,fill:'#bcf047'}),svgEl('text',{x:x(i),y:254,'text-anchor':'middle'},`W${t.week}`));s.append(g);});s.append(svgEl('text',{x:55,y:278},'LIME: SELECTED TEAM    DASH: LEAGUE AVG    BLUE: RANGE'));}
async function load(){const response=await fetch('league-data.json',{cache:'no-store'});if(!response.ok)throw Error('Snapshot unavailable');const next=await response.json();if(!next.teams?.length||!next.weeks?.length)throw Error('Invalid snapshot');const old=$('#week').value;data=next;const completed=data.weeks.map(w=>w.week),upcoming=completed.at(-1)+1;const options=[...completed,...(data.schedule.some(g=>g.week===upcoming)?[upcoming]:[])];$('#week').replaceChildren(...options.map(w=>{const o=node('option',`${w}${w===upcoming?' · Schedule only':''}`);o.value=w;return o;}));$('#week').value=options.includes(Number(old))?old:completed.at(-1);$('#week').disabled=false;const highlight=$('#chart-team').value;$('#chart-team').replaceChildren(...data.teams.map(t=>{const o=node('option',t.name);o.value=t.id;return o;}));if(data.teams.some(t=>t.id===highlight))$('#chart-team').value=highlight;$('#source').textContent=`${data.source} · Verified through Week ${completed.at(-1)} · Source snapshot ${new Date(data.source_updated).toLocaleString()} · Live scoring not connected.`;if(liveData)addLiveOption();render();if($('#detail').open&&selectedGame){const w=weekData();const g=w.matchups.find(g=>g.team_id===selectedGame.g.team_id&&g.opponent_id===selectedGame.g.opponent_id);if(g)openGame(g,w);else $('#detail').close();}}
$('#week').onchange=render;$('#chart-team').onchange=()=>renderTrend(Math.min(Number($('#week').value),data.weeks.at(-1).week));$('#close-detail').onclick=()=>$('#detail').close();$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
async function refresh(){const b=$('#refresh');b.disabled=true;try{await load();if(liveEndpoint)await pollLive();}catch(e){$('#status').textContent=data?'Refresh failed. Showing the last successfully loaded snapshot.':'League data could not load. Please try Refresh data.';}finally{b.disabled=false;}}
$('#refresh').onclick=refresh;
function gStatus(w){return w.matchups.every(g=>g.status==='final')?'Final feed results':w.matchups.some(g=>g.status==='live')?'Live scoring':'Pregame';}
function addLiveOption(){if(![...$('#week').options].some(o=>Number(o.value)===liveData.week)){const o=node('option',`${liveData.week} · Scoring feed`);o.value=liveData.week;$('#week').append(o);}}
async function pollLive(){try{const response=await fetch(liveEndpoint,{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(12000)});if(!response.ok)throw Error('Feed unavailable');const candidate=WFCLive.validate(await response.json(),data.teams,data.season);if(liveData&&Date.parse(candidate.updated_at)<Date.parse(liveData.updated_at))throw Error('Older feed');liveData=candidate;feedFailed=false;addLiveOption();}catch{feedFailed=true;}$('#feed-state').textContent=feedFailed?'Scoring feed unavailable':liveData&&WFCLive.stale(liveData)?'Scoring feed delayed':'Scoring feed connected';if(liveData){$('#feed-state').textContent+=` · ${new Date(liveData.updated_at).toLocaleTimeString()}`;render();if($('#detail').open&&selectedGame?.w.week===liveData.week){const g=liveData.matchups.find(g=>g.team_id===selectedGame.g.team_id&&g.opponent_id===selectedGame.g.opponent_id);if(g)openGame(g,liveData);}}}
async function init(){await refresh();try{const response=await fetch('live-config.json',{cache:'no-store'});const config=await response.json();if(config.endpoint){const url=new URL(config.endpoint,location.href);if(url.origin!==location.origin&&url.protocol!=='https:')throw Error('Unsafe feed URL');liveEndpoint=url.href;await pollLive();setInterval(()=>{if(!document.hidden)pollLive();},60000);}}catch{$('#feed-state').textContent='Live feed configuration unavailable';}}
init();
