'use strict';
const $ = selector => document.querySelector(selector);
const element = (tag, text = '', className = '') => { const node = document.createElement(tag); node.textContent = text; node.className = className; return node; };
const value = number => Number.isFinite(number) ? number.toFixed(1) : '—';
const columns = ['WR', 'RB', 'TE', 'QB'];
let data;
const nflCode = team => ({ WAS:'wsh', WSH:'wsh', JAC:'jax', JAX:'jax', SF:'sf', TB:'tb', GB:'gb', KC:'kc', NE:'ne', NO:'no', NYG:'nyg', NYJ:'nyj', LV:'lv', LAR:'lar', LAC:'lac' }[team] || String(team || '').toLowerCase());
function nflLogo(team) { const wrap=element('span','','nfl-logo');const image=document.createElement('img');image.src=`https://a.espncdn.com/i/teamlogos/nfl/500/${nflCode(team)}.png`;image.alt=`${team} logo`;image.loading='lazy';image.addEventListener('error',()=>{wrap.textContent=team;wrap.classList.add('nfl-logo-fallback');},{once:true});wrap.append(image);return wrap; }
function displayDate(date) { return date ? new Date(date).toLocaleString() : 'Awaiting permitted import'; }
function chart(points) {
  if (!points.length) return element('p', 'First market snapshot pending.', 'history-empty');
  const width=306,height=112,pad={left:29,right:8,top:10,bottom:25},values=points.map(point=>point.market_value),low=Math.floor((Math.min(...values)-2)/5)*5,high=Math.ceil((Math.max(...values)+2)/5)*5;
  const x=index=>pad.left+(width-pad.left-pad.right)*(points.length===1?.5:index/(points.length-1)); const y=number=>pad.top+(high-number)/Math.max(1,high-low)*(height-pad.top-pad.bottom);
  const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${width} ${height}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',`Market value history from ${points[0].date} to ${points.at(-1).date}`);
  [low,(low+high)/2,high].forEach(number=>{const line=document.createElementNS(svg.namespaceURI,'line');line.setAttribute('x1',pad.left);line.setAttribute('x2',width-pad.right);line.setAttribute('y1',y(number));line.setAttribute('y2',y(number));line.setAttribute('class','history-grid');svg.append(line);const label=document.createElementNS(svg.namespaceURI,'text');label.setAttribute('x',0);label.setAttribute('y',y(number)+4);label.textContent=number.toFixed(0);svg.append(label);});
  const path=document.createElementNS(svg.namespaceURI,'polyline');path.setAttribute('points',points.map((point,index)=>`${x(index)},${y(point.market_value)}`).join(' '));path.setAttribute('class','history-line');svg.append(path);
  [0,points.length-1].filter((item,index,all)=>all.indexOf(item)===index).forEach(index=>{const label=document.createElementNS(svg.namespaceURI,'text');label.setAttribute('x',x(index));label.setAttribute('y',height-4);label.setAttribute('text-anchor',index?'end':'start');label.textContent=new Date(points[index].date+'T12:00:00').toLocaleDateString(undefined,{month:'numeric',day:'numeric',year:'2-digit'});svg.append(label);});return svg;
}
function historyCard(item) { const card=element('aside','','history-popover'),title=element('div','','history-title');title.append(element('strong',item.player),element('span',`${item.nfl_team} · ${item.position}`));const measures=element('div','','history-measures');[['Market',item.market_value],['WFC value',item.value]].forEach(([label,number])=>{const measure=element('span');measure.append(element('small',label),element('b',value(number)));measures.append(measure);});const drivers=item.drivers?element('p',`Production ${value(item.drivers.production)} · Form ${value(item.drivers.recent_form)} · Outlook ${value(item.drivers.outlook)} · Role ${value(item.drivers.starting_role)}${item.drivers.superflex_qb?` · QB +${value(item.drivers.superflex_qb)}`:''}${item.drivers.news_impact?` · News ${item.drivers.news_impact>0?'+':''}${value(item.drivers.news_impact)}`:''}`,'driver-summary'):null;const note=item.news?.reason||item.override?.reason;card.append(title,measures,drivers||document.createDocumentFragment(),note?element('p',note,'driver-note'):document.createDocumentFragment(),chart(item.history||[]));return card; }
function playerCard(item,tierRow) { const card=element('button','','board-player');card.type='button';card.style.gridColumn=String(columns.indexOf(item.position)+1);card.style.gridRow=String(tierRow);card.setAttribute('aria-label',`${item.player}, ${item.position}, WFC market value ${value(item.market_value)}. Focus for value history and model drivers.`);const identity=element('span','','player-identity'),copy=element('span','','player-copy');copy.append(element('strong',item.player),element('small',`${item.nfl_team} · ${item.position}`));identity.append(nflLogo(item.nfl_team),copy);card.append(identity,element('span','⌁','history-icon'),historyCard(item));return card; }
function valueCell(item,tierRow) { const cell=element('div','','board-value');cell.style.gridColumn='5';cell.style.gridRow=String(tierRow);cell.setAttribute('aria-label',`${item.player} market value ${value(item.value)}`);cell.append(element('small','WFC'),element('b',value(item.value)));return cell; }
function renderBoard() { const board=$('#value-board');const items=data.market_board?.length?data.market_board:data.manual_board;board.replaceChildren();if(!items?.length){board.append(element('p','No WFC market snapshot is available yet. Run the Trade Alley refresh.','empty'));return;}const grouped=new Map();items.forEach(item=>{const tier=item.tier||'Unassigned';grouped.set(tier,[...(grouped.get(tier)||[]),item]);});[...grouped.entries()].sort(([left],[right])=>Number(left)-Number(right)||left.localeCompare(right)).forEach(([tier,tierItems])=>{const block=element('section','','tier-block');block.append(element('h3',`Tier ${tier}`,'tier-label'));const grid=element('div','','board-grid');columns.forEach(position=>grid.append(element('div',position==='WR'?'Wide Receiver':position==='RB'?'Running Back':position==='TE'?'Tight End':'Quarterback','position-header')));grid.append(element('div','Market value','position-header value-header'));const rows=new Map();tierItems.slice().sort((a,b)=>a.source_rank-b.source_rank).forEach((item,index)=>rows.set(item.player_id,index+2));tierItems.forEach(item=>{grid.append(playerCard(item,rows.get(item.player_id)),valueCell(item,rows.get(item.player_id)));});block.append(grid);board.append(block);}); }
function renderProviders() { $('#providers').replaceChildren(...data.providers.map(provider=>{const card=element('article','','provider'),heading=element('h3'),link=provider.source_url?document.createElement('a'):element('span');link.textContent=provider.name;if(provider.source_url){link.href=provider.source_url;link.target='_blank';link.rel='noopener noreferrer';}heading.append(link);card.append(heading,element('p',provider.status.replaceAll('_',' '),`provider-status ${provider.status==='active'?'active':''}`),element('p',provider.scoring_format),element('p',`Captured: ${displayDate(provider.captured_at)}`,'muted'),element('p',provider.notes,'muted'));return card;})); }
function init() { const model=data.providers.find(provider=>provider.id==='wfc-market-model'),board=data.market_board?.length?data.market_board:data.manual_board;const activeNews=data.market_model?.input_status?.active_news_signals??0;$('#updated').textContent=`WFC market model updated ${displayDate(model?.captured_at)} · ${board.length} players valued · ${activeNews} active news signals.`;$('#board-state').textContent=`${board.length} VALUES`;renderBoard();renderProviders(); }
fetch('data/trade-values.json',{cache:'no-store'}).then(response=>{if(!response.ok)throw Error('Trade snapshot unavailable');return response.json();}).then(snapshot=>{data=snapshot;init();}).catch(()=>{$('#updated').textContent='Trade Alley data could not load. Refresh to try again.';});
