'use strict';

const $ = selector => document.querySelector(selector);
const element = (tag, text = '', className = '') => { const node = document.createElement(tag); node.textContent = text; node.className = className; return node; };
const value = number => Number.isFinite(Number(number)) ? Number(number).toFixed(1) : '—';
const columns = ['WR', 'RB', 'TE', 'QB'];
let data, boardSearch = '', changeWindow = 'weekly';
const nflCode = team => ({ WAS: 'wsh', WSH: 'wsh', JAC: 'jax', JAX: 'jax', SF: 'sf', TB: 'tb', GB: 'gb', KC: 'kc', NE: 'ne', NO: 'no', NYG: 'nyg', NYJ: 'nyj', LV: 'lv', LAR: 'lar', LAC: 'lac' }[team] || String(team || '').toLowerCase());

function nflLogo(team) {
  const wrap = element('span', '', 'nfl-logo'); const image = document.createElement('img');
  image.src = `https://a.espncdn.com/i/teamlogos/nfl/500/${nflCode(team)}.png`; image.alt = `${team} logo`; image.loading = 'lazy';
  image.addEventListener('error', () => { wrap.textContent = team; wrap.classList.add('nfl-logo-fallback'); }, { once: true }); wrap.append(image); return wrap;
}
function displayDate(date) { return date ? new Date(date).toLocaleString() : 'Awaiting permitted import'; }
function pointDate(date, long = false) { return new Date(`${date}T12:00:00`).toLocaleDateString(undefined, long ? { month: 'short', day: 'numeric', year: 'numeric' } : { month: 'numeric', day: 'numeric', year: '2-digit' }); }
function trend(item) {
  const points = (item.history || []).filter(point => Number.isFinite(Number(point.market_value))).slice().sort((left, right) => String(left.date).localeCompare(String(right.date)));
  const latestPoint = points.at(-1), latest = latestPoint?.market_value ?? item.market_value;
  const weeklyCutoff = latestPoint?.date ? new Date(`${latestPoint.date}T12:00:00`).getTime() - 7 * 24 * 60 * 60 * 1000 : null;
  const previous = changeWindow === 'total'
    ? points[0]?.market_value
    : points.slice(0, -1).reverse().find(point => new Date(`${point.date}T12:00:00`).getTime() <= weeklyCutoff)?.market_value;
  const available = Number.isFinite(Number(previous));
  const units = available ? Math.round(Number(latest) - Number(previous)) : 0;
  const period = changeWindow === 'total' ? 'since preseason' : 'this week';
  return { units, available, title: changeWindow === 'total' ? 'Since preseason' : 'This week', className: !available ? 'neutral' : units > 0 ? 'positive' : units < 0 ? 'negative' : 'neutral', label: !available ? '—' : units > 0 ? `+${units}` : units < 0 ? String(units) : '—', aria: !available ? `${period} change pending another saved weekly snapshot` : units > 0 ? `${period}, up ${units} value units` : units < 0 ? `${period}, down ${Math.abs(units)} value units` : `${period}, no value change` };
}
function svgNode(name, attributes = {}) { const node = document.createElementNS('http://www.w3.org/2000/svg', name); Object.entries(attributes).forEach(([key, val]) => node.setAttribute(key, val)); return node; }
function chart(points, expanded = false) {
  const clean = points.filter(point => Number.isFinite(Number(point.market_value)));
  if (!clean.length) return element('p', 'First market snapshot pending.', 'history-empty');
  const width = expanded ? 980 : 306, height = expanded ? 380 : 112, pad = expanded ? { left: 58, right: 24, top: 22, bottom: 48 } : { left: 29, right: 8, top: 10, bottom: 25 };
  const values = clean.map(point => Number(point.market_value)), floor = Math.min(...values), ceiling = Math.max(...values), spread = Math.max(5, ceiling - floor);
  const low = Math.max(0, Math.floor((floor - spread * .22) / 5) * 5), high = Math.ceil((ceiling + spread * .22) / 5) * 5;
  const x = index => pad.left + (width - pad.left - pad.right) * (clean.length === 1 ? .5 : index / (clean.length - 1));
  const y = number => pad.top + (high - number) / Math.max(1, high - low) * (height - pad.top - pad.bottom);
  const svg = svgNode('svg', { viewBox: `0 0 ${width} ${height}`, role: 'img', 'aria-label': `Market value history from ${clean[0].date} to ${clean.at(-1).date}` });
  const tickCount = expanded ? 4 : 3;
  Array.from({ length: tickCount }, (_, index) => low + (high - low) * index / (tickCount - 1)).forEach(number => {
    const line = svgNode('line', { x1: pad.left, x2: width - pad.right, y1: y(number), y2: y(number), class: 'history-grid' }); const label = svgNode('text', { x: expanded ? 12 : 0, y: y(number) + 4 }); label.textContent = number.toFixed(0); svg.append(line, label);
  });
  svg.append(svgNode('polyline', { points: clean.map((point, index) => `${x(index)},${y(point.market_value)}`).join(' '), class: 'history-line' }));
  clean.forEach((point, index) => { const dot = svgNode('circle', { cx: x(index), cy: y(point.market_value), r: expanded ? 5.5 : 0, class: 'history-dot' }); const title = svgNode('title'); title.textContent = `${pointDate(point.date, true)} · ${value(point.market_value)}${point.kind === 'private_preseason_anchor' ? ' · preseason anchor' : ''}`; dot.append(title); if (expanded) svg.append(dot); });
  const labels = expanded ? clean.map((point, index) => ({ point, index })).filter(({ index }) => index === 0 || index === clean.length - 1 || (clean.length > 4 && index === Math.floor((clean.length - 1) / 2))) : [0, clean.length - 1].filter((item, index, all) => all.indexOf(item) === index).map(index => ({ point: clean[index], index }));
  labels.forEach(({ point, index }) => { const label = svgNode('text', { x: x(index), y: height - (expanded ? 14 : 4), 'text-anchor': index === 0 ? 'start' : index === clean.length - 1 ? 'end' : 'middle', class: 'history-date' }); label.textContent = pointDate(point.date); svg.append(label); }); return svg;
}
function historyCard(item) {
  const change = trend(item), card = element('aside', '', 'history-popover'), title = element('div', '', 'history-title'); title.append(element('strong', item.player), element('span', `${item.nfl_team} · ${item.position}`));
  const measures = element('div', '', 'history-measures'); [['Market', item.market_value], [change.title, change.label]].forEach(([label, number]) => { const measure = element('span', '', label === change.title ? `popover-change ${change.className}` : ''); measure.append(element('small', label), element('b', String(number))); measures.append(measure); });
  const drivers = item.drivers ? element('p', Number.isFinite(Number(item.drivers.forecast_ppg)) ? `V2 forecast ${value(item.drivers.forecast_ppg)} PPG · replacement ${value(item.drivers.replacement_ppg)} · VOR ${value(item.drivers.vor_ppg)} · availability ${Math.round(Number(item.drivers.availability || 0) * 100)}%` : `Production ${value(item.drivers.production)} · Form ${value(item.drivers.recent_form)} · Outlook ${value(item.drivers.outlook)} · Role ${value(item.drivers.starting_role)}${item.drivers.superflex_qb ? ` · QB +${value(item.drivers.superflex_qb)}` : ''}${item.drivers.news_impact ? ` · News ${item.drivers.news_impact > 0 ? '+' : ''}${value(item.drivers.news_impact)}` : ''}`, 'driver-summary') : null;
  const note = item.news?.reason || item.override?.reason, details = element('button', 'View details', 'details-button'); details.type = 'button'; details.addEventListener('click', event => { event.stopPropagation(); openTrend(item); });
  card.append(title, measures, drivers || document.createDocumentFragment(), note ? element('p', note, 'driver-note') : document.createDocumentFragment(), chart(item.history || []), details); return card;
}
function playerCard(item, tierRow) {
  const change = trend(item), card = element('article', '', `board-player ${change.className}${item.position === 'WR' ? ' first-column' : ''}`); card.style.gridColumn = String(columns.indexOf(item.position) + 1); card.style.gridRow = String(tierRow); card.tabIndex = 0;
  card.setAttribute('aria-label', `${item.player}, ${item.position}, WFC market value ${value(item.market_value)}, ${change.aria}. Focus for value history and model drivers.`);
  const identity = element('span', '', 'player-identity'), copy = element('span', '', 'player-copy'), meta = element('small'); meta.append(document.createTextNode(`${item.nfl_team} · `), element('b', `${item.position}${item.position_rank || '—'}`, `position-rank ${String(item.position).toLowerCase()}`)); copy.append(element('strong', item.player), meta); identity.append(nflLogo(item.nfl_team), copy);
  const changeNode = element('span', change.label, `value-change ${change.className}`); changeNode.setAttribute('aria-label', change.aria); const icon = element('span', '↗', 'history-icon'); icon.setAttribute('aria-hidden', 'true'); card.append(identity, changeNode, icon, historyCard(item)); return card;
}
function emptyCell(column, row) { const cell = element('div', '', `board-empty${column === 1 ? ' first-column' : ''}`); cell.style.gridColumn = String(column); cell.style.gridRow = String(row); cell.setAttribute('aria-hidden', 'true'); return cell; }
function valueCell(item, tierRow) { const cell = element('div', '', 'board-value'); cell.style.gridColumn = '5'; cell.style.gridRow = String(tierRow); cell.setAttribute('aria-label', `${item.player} market value ${value(item.market_value)}`); cell.append(element('small', 'WFC'), element('b', value(item.market_value))); return cell; }
function ensureTrendDialog() { let dialog = $('#trend-dialog'); if (dialog) return dialog; dialog = document.createElement('dialog'); dialog.id = 'trend-dialog'; dialog.className = 'trend-dialog'; dialog.addEventListener('click', event => { if (event.target === dialog) dialog.close(); }); document.body.append(dialog); return dialog; }
function openTrend(item) {
  const dialog = ensureTrendDialog(), change = trend(item), shell = element('section', '', 'trend-shell'), close = element('button', '×', 'trend-close'); close.type = 'button'; close.setAttribute('aria-label', 'Close value trend'); close.addEventListener('click', () => dialog.close());
  const eyebrow = element('p', 'WFC / MARKET HISTORY', 'eyebrow'), heading = element('h2', '3D value trend'), player = element('section', '', 'trend-player'), identity = element('div', '', 'trend-identity'), text = element('div'); text.append(element('h3', item.player), element('p', `${item.nfl_team} · ${item.position}`)); identity.append(nflLogo(item.nfl_team), text);
  const stats = element('div', '', 'trend-stats'); [['Market value', value(item.market_value)], [change.title, change.label]].forEach(([label, result]) => { const stat = element('div', '', label === change.title ? `trend-change ${change.className}` : ''); stat.append(element('small', label), element('strong', result)); stats.append(stat); }); player.append(identity, stats);
  const graph = element('section', '', 'trend-graph'); graph.append(chart(item.history || [], true), element('p', 'The first point is the private ESPN UDK-derived preseason anchor. Later points are saved WFC market snapshots; hover a plotted point for its date and value.', 'trend-note'));
  shell.append(close, eyebrow, heading, player, graph); dialog.replaceChildren(shell); dialog.showModal();
}
function selectedBoard() {
  return data.market_board?.length ? data.market_board : data.manual_board;
}
function renderBoard() {
  const board = $('#value-board'), allItems = selectedBoard(); board.replaceChildren(); if (!allItems?.length) { board.append(element('p', 'No WFC market snapshot is available yet. Run the Trade Alley refresh.', 'empty')); return; }
  const positionRanks = new Map(); columns.forEach(position => allItems.filter(item => item.position === position).sort((left, right) => Number(right.market_value) - Number(left.market_value) || left.player.localeCompare(right.player)).forEach((item, index) => positionRanks.set(item.player_id, index + 1))); const query = boardSearch.trim().toLowerCase(), items = query ? allItems.filter(item => `${item.player} ${item.position} ${item.nfl_team}`.toLowerCase().includes(query)) : allItems; const rankedItems = items.map(item => ({ ...item, position_rank: positionRanks.get(item.player_id) })); $('#board-state').textContent = `${items.length} ${items.length === 1 ? 'VALUE' : 'VALUES'}`;
  if (!rankedItems.length) { board.append(element('p', `No WFC market player matches “${boardSearch}”.`, 'empty')); return; }
  const grouped = new Map(); rankedItems.forEach(item => { const tier = item.tier || 'Unassigned'; grouped.set(tier, [...(grouped.get(tier) || []), item]); });
  [...grouped.entries()].sort(([left], [right]) => Number(left) - Number(right) || left.localeCompare(right)).forEach(([tier, tierItems]) => { const block = element('section', '', 'tier-block'), sortedTier = tierItems.slice().sort((a, b) => Number(a.market_rank ?? Infinity) - Number(b.market_rank ?? Infinity) || Number(b.market_value) - Number(a.market_value) || a.player.localeCompare(b.player)); block.append(element('h3', `Tier ${tier}`, 'tier-label')); const grid = element('div', '', 'board-grid'); columns.forEach((position, index) => grid.append(element('div', position === 'WR' ? 'Wide Receiver' : position === 'RB' ? 'Running Back' : position === 'TE' ? 'Tight End' : 'Quarterback', `position-header${index === 0 ? ' first-column' : ''}`))); grid.append(element('div', 'WFC market value', 'position-header value-header')); const rows = new Map(); sortedTier.forEach((item, index) => rows.set(item.player_id, index + 2)); for (let row = 2; row < tierItems.length + 2; row += 1) for (let column = 1; column <= 5; column += 1) grid.append(emptyCell(column, row)); sortedTier.forEach(item => grid.append(playerCard(item, rows.get(item.player_id)), valueCell(item, rows.get(item.player_id)))); block.append(grid); board.append(block); });
}
function renderProviders() { $('#providers').replaceChildren(...data.providers.map(provider => { const card = element('article', '', 'provider'), heading = element('h3'), link = provider.source_url ? document.createElement('a') : element('span'); link.textContent = provider.name; if (provider.source_url) { link.href = provider.source_url; link.target = '_blank'; link.rel = 'noopener noreferrer'; } heading.append(link); card.append(heading, element('p', provider.status.replaceAll('_', ' '), `provider-status ${provider.status === 'active' ? 'active' : ''}`), element('p', provider.scoring_format), element('p', `Captured: ${displayDate(provider.captured_at)}`, 'muted'), element('p', provider.notes, 'muted')); return card; })); }
function externalProviders() { return data.providers.filter(provider => provider.comparison_mode !== 'input_only' && !['wfc-manual', 'wfc-internal', 'wfc-market-model'].includes(provider.id)); }
function driverText(item) {
  if (!item?.drivers) return 'This player has no detailed driver record in the current snapshot.';
  const d = item.drivers, parts = [`production ${value(d.production)}`, `recent form ${value(d.recent_form)}`, `ROS outlook ${value(d.outlook)}`, `VOR ${value(d.vor_ppg)}`, `availability ${d.availability == null ? '—' : `${Math.round(Number(d.availability) * 100)}%`}`];
  if (d.market_shape_calibration_applied) parts.push(`market shape ${Math.round(Number(d.market_shape_weight) * 100)}% DraftSharks-calibrated`);
  if (d.superflex_qb) parts.push(`Superflex QB premium +${value(d.superflex_qb)}`); if (d.news_impact) parts.push(`news ${d.news_impact > 0 ? '+' : ''}${value(d.news_impact)}`);
  return `WFC is built from ${parts.join(' · ')}.`;
}
function comparisonRow(item, source) {
  const sourceRow = data.rows.find(row => row.provider_id === source.id && row.player_id === item.player_id), row = element('article', '', 'comparison-row');
  const direct = source.comparison_mode === 'direct', comparable = sourceRow && Number.isFinite(Number(direct ? sourceRow.raw_value : sourceRow.normalized_value)) ? Number(direct ? sourceRow.raw_value : sourceRow.normalized_value) : null;
  const name = element('div', '', 'comparison-player'); name.append(nflLogo(item.nfl_team), element('strong', item.player), element('small', `${item.position} · Tier ${item.tier}`));
  const dynamic = element('div', '', 'comparison-value'); dynamic.append(element('small', 'WFC dynamic'), element('b', value(item.market_value)));
  const external = element('div', '', 'comparison-value');
  if (comparable !== null) { external.append(element('small', direct ? 'WFC v2 shadow' : `${source.name} normalized`), element('b', value(comparable)), element('em', direct ? `rank #${sourceRow.source_rank} · uncapped` : sourceRow.raw_value !== null ? `raw ${value(sourceRow.raw_value)}${sourceRow.source_rank ? ` · #${sourceRow.source_rank}` : ''}` : sourceRow.source_rank ? `rank #${sourceRow.source_rank}` : 'ranked source')); } else external.append(element('small', `${source.name} normalized`), element('b', '—'), element('em', 'No permitted snapshot'));
  const delta = comparable !== null ? Math.round((Number(item.market_value) - comparable) * 10) / 10 : null, difference = element('div', '', `comparison-value delta ${delta === null ? '' : delta > 0 ? 'positive' : delta < 0 ? 'negative' : 'neutral'}`); difference.append(element('small', direct ? 'v1 → v2' : 'WFC delta'), element('b', delta === null ? '—' : `${delta > 0 ? '+' : ''}${value(delta)}`), element('em', delta === null ? 'Needs import' : delta > 0 ? 'WFC higher' : delta < 0 ? 'WFC lower' : 'Aligned'));
  const why = element('button', 'Why?', 'why-button'); why.type = 'button'; why.addEventListener('click', () => updateComparisonFocus(item, source, sourceRow)); row.append(name, dynamic, external, difference, why); return row;
}
function updateComparisonFocus(item, source, sourceRow) {
  const focus = $('#comparison-focus'); if (!focus) return; focus.replaceChildren();
  const heading = element('h3', `Why ${item.player}?`), copy = element('p', driverText(item)); focus.append(heading, copy);
  const direct = source.comparison_mode === 'direct', comparable = sourceRow && Number.isFinite(Number(direct ? sourceRow.raw_value : sourceRow.normalized_value)) ? Number(direct ? sourceRow.raw_value : sourceRow.normalized_value) : null;
  if (comparable !== null) { const delta = Math.round((Number(item.market_value) - comparable) * 10) / 10; focus.append(element('p', direct ? `Shadow v2 is ${Math.abs(delta).toFixed(1)} points ${delta >= 0 ? 'below' : 'above'} live v1. This first pass has no external-market drift cap.` : `WFC is ${Math.abs(delta).toFixed(1)} normalized points ${delta >= 0 ? 'above' : 'below'} ${source.name}. Raw provider values stay separate: the comparison uses each source’s within-source percentile, never a raw-value average.`, 'comparison-answer')); if (direct && sourceRow.drivers) { const d = sourceRow.drivers; focus.append(element('p', `V2: ${value(d.forecast_ppg)} forecast PPG · ${value(d.replacement_ppg)} replacement PPG · ${value(d.vor_ppg)} value over replacement · availability ${Math.round(Number(d.availability || 0) * 100)}%.`, 'comparison-news')); if (Number.isFinite(Number(d.nflverse_usage_score))) focus.append(element('p', `Public nflverse inputs: usage ${value(d.nflverse_usage_score)}th percentile · efficiency ${value(d.nflverse_efficiency_score)}th percentile · ${d.nflverse_usage_adjustment_ppg >= 0 ? '+' : ''}${value(d.nflverse_usage_adjustment_ppg)} usage PPG · ${d.nflverse_efficiency_adjustment_ppg >= 0 ? '+' : ''}${value(d.nflverse_efficiency_adjustment_ppg)} efficiency PPG. These are within-position signals, not outside trade values.`, 'comparison-news')); } }
  else focus.append(element('p', `${source.name} has not been imported as a reviewed, permitted Superflex snapshot yet. Once it is, this panel will show the normalized gap and preserve its raw value/rank alongside it.`, 'comparison-answer'));
  if (item.news?.reason || item.override?.reason) focus.append(element('p', item.news?.reason || item.override?.reason, 'comparison-news'));
}
function renderComparison() {
  const providerSelect = $('#comparison-provider'), playerSelect = $('#comparison-player'), list = $('#comparison-list'), board = data.market_board?.length ? data.market_board : data.manual_board, providers = externalProviders(); providerSelect.replaceChildren();
  providers.forEach(provider => { const option = element('option', provider.name); option.value = provider.id; providerSelect.append(option); });
  const draftSharks = providers.find(provider => provider.id === 'draftsharks' && provider.status === 'active'); if (draftSharks) providerSelect.value = draftSharks.id;
  playerSelect.replaceChildren(); board.forEach(item => { const option = element('option', item.player); option.value = item.player_id; playerSelect.append(option); });
  const paint = () => { const source = providers.find(provider => provider.id === providerSelect.value) || providers[0], selected = board.find(item => item.player_id === playerSelect.value) || board[0]; list.replaceChildren(...board.slice().sort((left, right) => right.market_value - left.market_value).map(item => comparisonRow(item, source))); updateComparisonFocus(selected, source, data.rows.find(row => row.provider_id === source.id && row.player_id === selected.player_id)); const direct = source.comparison_mode === 'direct', status = direct ? 'Shadow review generated from current WFC data.' : source.status === 'active' ? `Reviewed snapshot captured ${displayDate(source.captured_at)}.` : 'Awaiting a reviewed, permitted Superflex snapshot.'; $('#comparison-status').textContent = direct ? `${status} v1 and v2 share a 0–100 scale; drift is intentionally uncapped for this pass.` : `${status} Raw values are shown for context; delta uses a 0–100 within-source normalized value.`; };
  providerSelect.addEventListener('change', paint); playerSelect.addEventListener('change', paint); paint();
}
function init() { const model = data.providers.find(provider => provider.id === 'wfc-market-model'), board = data.market_board?.length ? data.market_board : data.manual_board, activeNews = data.market_model?.input_status?.active_news_signals ?? 0, usagePlayers = data.market_model?.input_status?.nflverse_players_matched ?? 0, footclanStatus = data.market_model?.input_status?.footclan_private_status, footclanPlayers = data.market_model?.input_status?.footclan_private_rankings_matched ?? 0, anchorProfile = data.market_model?.input_status?.preseason_anchor_profile || 'private anchor pending', anchorPlayers = data.market_model?.input_status?.preseason_anchor_players_matched ?? 0, footclanLabel = footclanStatus ? ` · ${footclanStatus.replaceAll('_', ' ')} private FootClan capture (${footclanPlayers} matched)` : '', search = $('#player-search'), windowSelect = $('#change-window'), windowNote = $('#change-window-note'); $('#updated').textContent = `WFC v2 market model updated ${displayDate(model?.captured_at)} · ${board.length} players valued · ${anchorPlayers} preseason anchors (${anchorProfile}) · ${usagePlayers} public usage inputs · ${activeNews} active news signals${footclanLabel}.`; search.addEventListener('input', () => { boardSearch = search.value; renderBoard(); }); windowSelect.addEventListener('change', () => { changeWindow = windowSelect.value; windowNote.textContent = changeWindow === 'weekly' ? 'Weekly change uses the closest saved value at least seven days earlier.' : 'Total market change compares the live value with the preseason anchor.'; renderBoard(); }); renderBoard(); renderComparison(); renderProviders(); }
fetch('data/trade-values.json', { cache: 'no-store' }).then(response => { if (!response.ok) throw Error('Trade snapshot unavailable'); return response.json(); }).then(snapshot => { data = snapshot; init(); }).catch(() => { $('#updated').textContent = 'Trade Alley data could not load. Refresh to try again.'; });
