'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = process.argv[2] || path.resolve(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'data', 'trade-values.json'), 'utf8'));
const model = JSON.parse(fs.readFileSync(path.join(root, 'data', 'wfc-market-model.json'), 'utf8'));
const history = JSON.parse(fs.readFileSync(path.join(root, 'data', 'market-history.json'), 'utf8'));

assert.equal(data.schema_version, '1.0.0');
assert.deepEqual(data.league_rules, { teams: 12, scoring: 'full PPR', starters: ['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'SUPERFLEX', 'D/ST', 'K'], passing_touchdown_points: 4, quarterback_cap: 3 });
assert.match(data.consensus_method, /never averaged/i);
assert(data.providers.some(provider => provider.id === 'draftsharks'));
assert.equal(data.providers.find(provider => provider.id === 'draftsharks').status, 'manual_or_licensed_import_required');
assert(data.providers.some(provider => provider.id === 'wfc-internal' && provider.status === 'active'));
assert(data.providers.some(provider => provider.id === 'wfc-market-model' && provider.status === 'active'));
assert(data.providers.some(provider => provider.id === 'wfc-market-v2-shadow' && provider.status === 'shadow_review' && provider.comparison_mode === 'direct'));
assert(data.providers.some(provider => provider.id === 'nflverse-weekly' && provider.status === 'active' && provider.comparison_mode === 'input_only'));
assert(data.providers.some(provider => provider.id === 'espn'));
assert.equal(model.model_id, 'wfc-market-v1');
assert.equal(model.players.length, data.market_board.length);
assert.equal(model.shadow_v2.model_id, 'wfc-market-v2-shadow');
assert.equal(model.shadow_v2.status, 'review_only_uncapped_drift');
assert.equal(model.shadow_v2.players.length, model.players.length);
assert(model.shadow_v2.players.every(player => Number.isFinite(player.value) && player.value >= 0 && player.value <= 100));
assert(data.rows.filter(row => row.provider_id === 'wfc-market-v2-shadow').every(row => Number.isFinite(row.raw_value) && Number.isFinite(row.normalized_value)));
assert(model.players.every(player => Number.isFinite(player.value) && player.value >= 0 && player.value <= 100));
assert(model.players.every(player => Number.isFinite(player.drivers.production) && Number.isFinite(player.drivers.outlook)));
assert.equal(model.input_status.active_news_signals, 0);
assert(model.input_status.nflverse_players_matched >= 160);
assert(history.snapshots[model.history_date]);
assert.equal(Object.keys(history.snapshots[model.history_date]).length, model.players.length);
assert.equal(data.manual_board.length, 7);
const amon = data.manual_board.find(player => player.player === 'Amon-Ra St. Brown');
assert.equal(amon.tier, '1');
assert.equal(amon.market_value, 79.3);
assert.equal(amon.history.length, 8);
assert.equal(amon.history.at(-1).date, '2026-10-07');
assert(data.players.find(player => player.name === 'Amon-Ra St. Brown'));
assert(data.players.find(player => player.name === 'Bryce Young'));
assert(data.rows.filter(row => row.provider_id === 'wfc-internal').every(row => Number.isFinite(row.normalized_value) && Number.isFinite(row.wfc_value)));
assert.equal(data.default_trade.left.length, 1);
assert.equal(data.default_trade.right.length, 2);
const limp = data.teams.find(team => team.id === 'WFC_ESPN_14');
assert.equal(limp.quarterbacks.length, 3);
console.log('PASS: Trade Alley schema, market model/history, source safeguards, normalization, WFC rules, and default 3-QB-cap scenario validated.');
