'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = process.argv[2] || path.resolve(__dirname, '..');
const data = JSON.parse(fs.readFileSync(path.join(root, 'data', 'trade-values.json'), 'utf8'));
const model = JSON.parse(fs.readFileSync(path.join(root, 'data', 'wfc-market-model.json'), 'utf8'));
const history = JSON.parse(fs.readFileSync(path.join(root, 'data', 'market-history.json'), 'utf8'));

assert.equal(data.schema_version, '1.0.0');
assert.deepEqual(data.league_rules, { teams: 12, scoring: 'full PPR', starters: ['QB', 'RB', 'RB', 'WR', 'WR', 'TE', 'FLEX', 'SUPERFLEX', 'D/ST', 'K'], passing_touchdown_points: 4, quarterback_cap: 3 });
assert.match(data.consensus_method, /never averaged/i);
assert(data.providers.some(provider => provider.id === 'draftsharks'));
assert.equal(data.providers.find(provider => provider.id === 'draftsharks').status, 'active');
assert.equal(data.rows.filter(row => row.provider_id === 'draftsharks').length, 12);
assert(data.providers.some(provider => provider.id === 'wfc-internal' && provider.status === 'active'));
assert(data.providers.some(provider => provider.id === 'wfc-market-model' && provider.status === 'active'));
assert(data.providers.some(provider => provider.id === 'footclan-private-inputs' && provider.status === 'partial_current_capture' && provider.comparison_mode === 'input_only'));
assert(data.providers.some(provider => provider.id === 'nflverse-weekly' && provider.status === 'active' && provider.comparison_mode === 'input_only'));
assert(data.providers.some(provider => provider.id === 'espn'));
assert.equal(model.model_id, 'wfc-market-v4-weekly-results');
assert.equal(model.players.length, data.market_board.length);
assert.equal(model.shadow_v2.model_id, 'wfc-market-v2-core');
assert.equal(model.shadow_v2.status, 'live_component');
assert.equal(model.shadow_v2.players.length, model.players.length);
assert(model.shadow_v2.players.every(player => Number.isFinite(player.value) && player.value >= 0 && player.value <= 100));
assert(model.players.every(player => Number.isFinite(player.value) && player.value >= 0 && player.value <= 100));
assert(model.players.every(player => Number.isFinite(player.drivers.production) && Number.isFinite(player.drivers.outlook)));
assert.equal(model.input_status.footclan_private_status, 'partial_current_capture');
assert(model.input_status.footclan_private_rankings_matched > 0);
assert(model.shadow_v2.players.some(player => player.drivers.private_forward_input_applied));
assert.equal(model.input_status.preseason_anchor_profile, 'Limp Brizkit — ESPN');
assert(model.input_status.preseason_anchor_players_matched >= 160);
assert.equal(model.input_status.market_shape_calibration_provider, 'DraftSharks');
assert.equal(model.input_status.market_shape_calibration_date, '2026-10-07');
assert(model.input_status.market_shape_calibration_players_matched >= 150);
assert(!JSON.stringify(data).includes('weekly_projection'));
assert(!JSON.stringify(data).includes('expert_ranks'));
assert.equal(model.input_status.active_news_signals, 0);
assert(model.input_status.nflverse_players_matched >= 160);
assert(history.snapshots[model.history_date]);
assert.equal(Object.keys(history.snapshots[model.history_date]).length, model.players.length);
assert(history.snapshot_metadata['2026-08-29']);
assert.equal(history.snapshot_metadata['2026-08-29'].kind, 'private_preseason_anchor');
assert(history.snapshot_metadata['2026-10-06']);
assert.equal(history.snapshot_metadata['2026-10-06'].kind, 'weekly_results_checkpoint');
assert(data.market_board.every(player => player.history.some(point => point.kind === 'weekly_results_checkpoint')));
assert.equal(data.manual_board.length, 7);
const amon = data.manual_board.find(player => player.player === 'Amon-Ra St. Brown');
assert.equal(amon.tier, '1');
assert.equal(amon.market_value, 79.3);
assert.equal(amon.history.length, 8);
assert.equal(amon.history.at(-1).date, '2026-10-07');
assert(data.players.find(player => player.name === 'Amon-Ra St. Brown'));
assert(data.players.find(player => player.name === 'Bryce Young'));
assert(data.rows.filter(row => row.provider_id === 'wfc-internal').every(row => Number.isFinite(row.normalized_value) && Number.isFinite(row.wfc_value)));
assert.equal(data.default_trade.left.length, 1);
assert.equal(data.default_trade.right.length, 2);
const limp = data.teams.find(team => team.id === 'WFC_ESPN_14');
assert.equal(limp.quarterbacks.length, 3);
console.log('PASS: Trade Alley schema, market model/history, source safeguards, normalization, WFC rules, and default 3-QB-cap scenario validated.');
